/*
 * test_add_three_symbolic_keys_preserves_validity.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_add_three_symbolic_keys_preserves_validity.c ../../ex2/treetable.c \
 *         -o test_add_three_symbolic_keys_preserves_validity && ./test_add_three_symbolic_keys_preserves_validity
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case1(void) {
        int k1=65536, k2=16777216, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 2 — from test000002.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case2(void) {
        int k1=-2147483647, k2=-2147483648, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 3 — from test000003.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case3(void) {
        int k1=33554432, k2=16777216, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 4 — from test000004.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case4(void) {
        int k1=-2147483640, k2=-1073741824, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 5 — from test000005.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case5(void) {
        int k1=-1996488704, k2=16777216, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 6 — from test000006.ktest */
static void test_add_three_symbolic_keys_preserves_validity_case6(void) {
        int k1=61695, k2=-2147483648, k3=0;
        int v1=0, v2=0, v3=0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_add(table, &k3, &v3) == CC_OK);
        assert(treetable_size(table) == 3);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

int main(void) {
    test_add_three_symbolic_keys_preserves_validity_case1();
    test_add_three_symbolic_keys_preserves_validity_case2();
    test_add_three_symbolic_keys_preserves_validity_case3();
    test_add_three_symbolic_keys_preserves_validity_case4();
    test_add_three_symbolic_keys_preserves_validity_case5();
    test_add_three_symbolic_keys_preserves_validity_case6();
    printf("test_add_three_symbolic_keys_preserves_validity: %d case(s) passed.\n", 6);
    return 0;
}
