/*
 * test_get_first_key_is_minimum.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_get_first_key_is_minimum.c ../../ex2/treetable.c \
 *         -o test_get_first_key_is_minimum && ./test_get_first_key_is_minimum
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_get_first_key_is_minimum_case1(void) {
        int k1=65536, k2=16777216, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

/* case 2 — from test000002.ktest */
static void test_get_first_key_is_minimum_case2(void) {
        int k1=-2147483647, k2=-2147483648, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

/* case 3 — from test000003.ktest */
static void test_get_first_key_is_minimum_case3(void) {
        int k1=33554432, k2=16777216, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

/* case 4 — from test000004.ktest */
static void test_get_first_key_is_minimum_case4(void) {
        int k1=-2147483640, k2=-1073741824, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

/* case 5 — from test000005.ktest */
static void test_get_first_key_is_minimum_case5(void) {
        int k1=61695, k2=-2147483648, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

/* case 6 — from test000006.ktest */
static void test_get_first_key_is_minimum_case6(void) {
        int k1=-1996488704, k2=16777216, k3=0, val=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &val) == CC_OK);
        assert(treetable_add(table, &k2, &val) == CC_OK);
        assert(treetable_add(table, &k3, &val) == CC_OK);
        assert(treetable_get_first_key(table, &out) == CC_OK);
        assert(*(int*)out <= k1 && *(int*)out <= k2 && *(int*)out <= k3);
        treetable_destroy(table);
}

int main(void) {
    test_get_first_key_is_minimum_case1();
    test_get_first_key_is_minimum_case2();
    test_get_first_key_is_minimum_case3();
    test_get_first_key_is_minimum_case4();
    test_get_first_key_is_minimum_case5();
    test_get_first_key_is_minimum_case6();
    printf("test_get_first_key_is_minimum: %d case(s) passed.\n", 6);
    return 0;
}
