/*
 * test_add_duplicate_updates_value_only.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_add_duplicate_updates_value_only.c ../../ex2/treetable.c \
 *         -o test_add_duplicate_updates_value_only && ./test_add_duplicate_updates_value_only
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_add_duplicate_updates_value_only_case1(void) {
        int key       = 0;
        int old_value = 0;
        int new_value = 0;
        void *out     = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &key, &old_value) == CC_OK);
        assert(treetable_add(table, &key, &new_value) == CC_OK);
        assert(treetable_size(table) == 1);
        assert(treetable_get(table, &key, &out) == CC_OK);
        assert(out == &new_value);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

int main(void) {
    test_add_duplicate_updates_value_only_case1();
    printf("test_add_duplicate_updates_value_only: %d case(s) passed.\n", 1);
    return 0;
}
