/*
 * test_get_greater_than_uses_right_subtree_minimum.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_get_greater_than_uses_right_subtree_minimum.c ../../ex2/treetable.c \
 *         -o test_get_greater_than_uses_right_subtree_minimum && ./test_get_greater_than_uses_right_subtree_minimum
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_get_greater_than_uses_right_subtree_minimum_case1(void) {
        int k1=10, k2=20, k3=30, value=0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k2, &value) == CC_OK);
        assert(treetable_add(table, &k1, &value) == CC_OK);
        assert(treetable_add(table, &k3, &value) == CC_OK);
        assert(treetable_get_greater_than(table, &k2, &out) == CC_OK);
        assert(*(int*)out == k3);
        treetable_destroy(table);
}

int main(void) {
    test_get_greater_than_uses_right_subtree_minimum_case1();
    printf("test_get_greater_than_uses_right_subtree_minimum: %d case(s) passed.\n", 1);
    return 0;
}
