/*
 * test_add_root_preserves_validity.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_add_root_preserves_validity.c ../../ex2/treetable.c \
 *         -o test_add_root_preserves_validity && ./test_add_root_preserves_validity
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_add_root_preserves_validity_case1(void) {
        int key   = 0;
        int value = 0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &key, &value) == CC_OK);
        assert(treetable_size(table) == 1);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

int main(void) {
    test_add_root_preserves_validity_case1();
    printf("test_add_root_preserves_validity: %d case(s) passed.\n", 1);
    return 0;
}
