/*
 * test_get_greater_than_maximum_key_is_total.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_get_greater_than_maximum_key_is_total.c ../../ex2/treetable.c \
 *         -o test_get_greater_than_maximum_key_is_total && ./test_get_greater_than_maximum_key_is_total
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_get_greater_than_maximum_key_is_total_case1(void) {
        int k1=10, k2=20, value=0;
        void *out = NULL;
        enum cc_stat status;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &value) == CC_OK);
        assert(treetable_add(table, &k2, &value) == CC_OK);
        status = treetable_get_greater_than(table, &k2, &out);
        assert(status == CC_OK || status == CC_ERR_KEY_NOT_FOUND);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

int main(void) {
    test_get_greater_than_maximum_key_is_total_case1();
    printf("test_get_greater_than_maximum_key_is_total: %d case(s) passed.\n", 1);
    return 0;
}
