/*
 * test_get_greater_than_internal_null_successor_branch.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_get_greater_than_internal_null_successor_branch.c ../../ex2/treetable.c \
 *         -o test_get_greater_than_internal_null_successor_branch && ./test_get_greater_than_internal_null_successor_branch
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_get_greater_than_internal_null_successor_branch_case1(void) {
        TreeTable table; RBNode node;
        int key=0, value=0;
        void *out = NULL;
        table.root=&node; table.sentinel=NULL; table.size=1;
        table.cmp=cmp; table.mem_alloc=malloc;
        table.mem_calloc=calloc; table.mem_free=free;
        node.key=&key; node.value=&value; node.color=RB_BLACK;
        node.parent=NULL; node.left=NULL; node.right=NULL;
        assert(treetable_get_greater_than(&table, &key, &out) == CC_ERR_KEY_NOT_FOUND);
}

int main(void) {
    test_get_greater_than_internal_null_successor_branch_case1();
    printf("test_get_greater_than_internal_null_successor_branch: %d case(s) passed.\n", 1);
    return 0;
}
