/*
 * test_get_missing_keys_fail.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_get_missing_keys_fail.c ../../ex2/treetable.c \
 *         -o test_get_missing_keys_fail && ./test_get_missing_keys_fail
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_get_missing_keys_fail_case1(void) {
        int absent_empty = 0, present = 16777216;
        int absent_ne    = 0, value  = 0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_get(table, &absent_empty, &out) == CC_ERR_KEY_NOT_FOUND);
        assert(treetable_add(table, &present, &value) == CC_OK);
        assert(treetable_get(table, &absent_ne, &out) == CC_ERR_KEY_NOT_FOUND);
        treetable_destroy(table);
}

/* case 2 — from test000002.ktest */
static void test_get_missing_keys_fail_case2(void) {
        int absent_empty = 0, present = 0;
        int absent_ne    = 16777217, value  = 0;
        void *out = NULL;
        TreeTable *table = make_table_default();
        assert(treetable_get(table, &absent_empty, &out) == CC_ERR_KEY_NOT_FOUND);
        assert(treetable_add(table, &present, &value) == CC_OK);
        assert(treetable_get(table, &absent_ne, &out) == CC_ERR_KEY_NOT_FOUND);
        treetable_destroy(table);
}

int main(void) {
    test_get_missing_keys_fail_case1();
    test_get_missing_keys_fail_case2();
    printf("test_get_missing_keys_fail: %d case(s) passed.\n", 2);
    return 0;
}
