/*
 * test_add_left_and_right_children.c — concrete test suite derived from KLEE output.
 * Auto-generated by decode_klee.py — do not edit manually.
 *
 * Build (example):
 *   clang -fprofile-instr-generate -fcoverage-mapping \
 *         test_add_left_and_right_children.c ../../ex2/treetable.c \
 *         -o test_add_left_and_right_children && ./test_add_left_and_right_children
 */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "../../ex2/treetable.c"

static TreeTable *make_table_default(void) {
    TreeTable *table = NULL;
    TreeTableConf conf;
    treetable_conf_init(&conf);
    assert(treetable_new_conf(&conf, &table) == CC_OK);
    return table;
}

/* case 1 — from test000001.ktest */
static void test_add_left_and_right_children_case1(void) {
        int k1 = 16777216, k2 = 0, v1 = 0, v2 = 0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_size(table) == 2);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

/* case 2 — from test000002.ktest */
static void test_add_left_and_right_children_case2(void) {
        int k1 = 0, k2 = 16777217, v1 = 0, v2 = 0;
        TreeTable *table = make_table_default();
        assert(treetable_add(table, &k1, &v1) == CC_OK);
        assert(treetable_add(table, &k2, &v2) == CC_OK);
        assert(treetable_size(table) == 2);
        assert(balanced(table));
        assert(sorted(table));
        treetable_destroy(table);
}

int main(void) {
    test_add_left_and_right_children_case1();
    test_add_left_and_right_children_case2();
    printf("test_add_left_and_right_children: %d case(s) passed.\n", 2);
    return 0;
}
